import io
from datetime import datetime
from typing import Any

from agents.base import BaseAgent


class ReportingAgent(BaseAgent):
    name = "ReportingAgent"
    description = "Generates PDF/Excel reports and executive summaries"

    async def execute(self, context: dict[str, Any]) -> dict[str, Any]:
        extracted = context.get("extracted_invoice", {})
        exceptions = context.get("exceptions", [])
        recommendation = context.get("recommendation")
        risk_score = context.get("risk_score")

        executive_summary = self._generate_executive_summary(extracted, exceptions, recommendation, risk_score)
        audit_report = self._generate_audit_report(context)
        pdf_bytes = self._generate_pdf_report(executive_summary, audit_report)

        insight = self._create_insight(
            reasoning=f"Generated executive summary and audit report for invoice {extracted.get('invoice_number', 'N/A')}.",
            confidence=0.95,
            evidence=["Executive summary", "Audit trail report", "Exception analysis"],
            next_action="Distribute report to stakeholders",
        )

        return {
            "executive_summary": executive_summary,
            "audit_report": audit_report,
            "pdf_report_size": len(pdf_bytes),
            "report_generated_at": datetime.utcnow().isoformat(),
            "insight": insight,
        }

    def _generate_executive_summary(self, extracted: dict, exceptions: list, recommendation, risk_score) -> str:
        inv_num = extracted.get("invoice_number", "N/A")
        vendor = extracted.get("vendor_name", "Unknown")
        amount = extracted.get("total_amount", 0)
        currency = extracted.get("currency", "USD")

        risk_level = "LOW"
        if risk_score is not None:
            if hasattr(risk_score, "risk_level"):
                risk_level = str(risk_score.risk_level.value).upper()
            elif isinstance(risk_score, dict):
                risk_level = str(risk_score.get("risk_level", "low")).upper()
            elif isinstance(risk_score, (int, float)):
                # risk_score passed as a 0-100 numeric score
                if risk_score >= 80:
                    risk_level = "CRITICAL"
                elif risk_score >= 50:
                    risk_level = "HIGH"
                elif risk_score >= 20:
                    risk_level = "MEDIUM"
                else:
                    risk_level = "LOW"

        rec_text = "Auto-approve"
        if recommendation:
            rec_text = recommendation.approval_recommendation if hasattr(recommendation, "approval_recommendation") else recommendation.get("approval_recommendation", "")

        return f"""EXECUTIVE SUMMARY — Invoice {inv_num}

Vendor: {vendor}
Amount: {currency} {amount:,.2f}
Risk Level: {risk_level}
Exceptions: {len(exceptions)}
Recommendation: {rec_text}

{'Key Issues: ' + '; '.join(e.title if hasattr(e, 'title') else e.get('title', '') for e in exceptions[:3]) if exceptions else 'No exceptions detected. Invoice is compliant and ready for processing.'}

Generated by AP Invoice & Contract Exception Agent
{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"""

    def _generate_audit_report(self, context: dict) -> dict:
        insights = context.get("all_insights", [])
        return {
            "pipeline_stages": [
                "Document Intake",
                "Invoice Understanding",
                "Contract Intelligence",
                "PO Matching",
                "Finance Policy",
                "Exception Detection",
                "Fraud Intelligence",
                "Recommendation",
                "Workflow Routing",
            ],
            "agent_count": len(insights),
            "decisions": [
                {
                    "agent": i.agent_name if hasattr(i, "agent_name") else i.get("agent_name"),
                    "confidence": i.confidence if hasattr(i, "confidence") else i.get("confidence"),
                    "summary": (i.reasoning if hasattr(i, "reasoning") else i.get("reasoning", ""))[:200],
                }
                for i in insights
            ],
            "timestamp": datetime.utcnow().isoformat(),
        }

    def _generate_pdf_report(self, summary: str, audit: dict) -> bytes:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas

            buffer = io.BytesIO()
            c = canvas.Canvas(buffer, pagesize=letter)
            c.setFont("Helvetica-Bold", 16)
            c.drawString(50, 750, "AP Invoice Exception Report")
            c.setFont("Helvetica", 10)
            y = 720
            for line in summary.split("\n"):
                c.drawString(50, y, line[:90])
                y -= 14
            c.save()
            return buffer.getvalue()
        except Exception:
            return summary.encode("utf-8")
